server:
  port: 8085

spring:
  application:
    name: audit-filter-demo
  autoconfigure:
    exclude:
      - org.springframework.boot.jms.autoconfigure.JmsAutoConfiguration
      - org.springframework.boot.artemis.autoconfigure.ArtemisAutoConfiguration
cp:
  audit:
    enabled: ${AUDIT_ENABLED:true}
    block-on-failure: ${AUDIT_BLOCK_ON_FAILURE:true}
    hosts:
      - ${ARTEMIS_HOST_PRIMARY:localhost}
      - ${ARTEMIS_HOST_SECONDARY:localhost}
