name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  Test-Modules:
    name: Test ${{ matrix.module }}
    strategy:
      matrix:
        module: [ actuator-demo,
                  controller-demo,
                  flyway-java-migration-demo,
                  # audit-filter-demo - need to fix up the audit-filter version post merge
                  auth-filter-demo,
                  json-mapper-demo,
                  jwt-token-demo,
                  exception-handling-demo,
                  openapi-client-demo,
          # clock-demo - Not work in pipeline. Oddly
                  postgres-encrypt-demo,
                  postgres-lock,
                  postgres-springboot4,
                  servicebus-retry-demo,
                  servicebus-queue-demo,
                  servicebus-topic-demo,
          #        azure-azureite-storage
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Module tests
        env:
          AZURITE_ACCOUNT_KEY: ${{ vars.AZURITE_ACCOUNT_KEY }}
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
        run: |
          cd ${{ matrix.module }}
          pwd
          ./gradlew clean test
          cd ..


