name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  Test-Modules:
    name: Test ${{ matrix.module }}
    strategy:
      matrix:
        module: [ actuator-demo,
                  audit-filter-demo,
                  auth-filter-demo,
                  json-mapper-demo,
                  jwt-token-demo,
                  exception-handling-demo,
                  openapi-client-demo,
          # clock-demo - Not work in pipeline. Oddly
                  postgres-lock,
                  postgres-springboot4,
                  servicebus-retry-demo,
                  servicebus-queue-demo,
                  servicebus-topic-demo ]
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ vars.AZURE_STORAGE_CONNECTION_STRING }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Module tests
        run: |
          env
          echo "vars.AZURE_STORAGE_CONNECTION_STRING is set to \"${{ vars.AZURE_STORAGE_CONNECTION_STRING }}\""
          echo "AZURE_STORAGE_CONNECTION_STRING is set to \"${AZURE_STORAGE_CONNECTION_STRING}\""
          cd ${{ matrix.module }}
          pwd
          ./gradlew clean test
          cd ..


